version: '3'

services:
  publication.service:
    image: publication.service
    build:
      context: .
      dockerfile: Publication.Service/Dockerfile
    ports:
      - "8000:80"
    depends_on: 
      - rabbitMQ

  rabbitMQ:
    image: "rabbitmq:3-management"   
    ports:
      - "15672:15672"
      - "5672:5672" 
   
  postgres:
    image: "postgres"
    restart: unless-stopped
    environment:
      - "POSTGRES_DB:RabbitConsumer"
      - "POSTGRES_USER:nazmul"
      - "POSTGRES_PASSWORD:P2qN9MVEv2Gn"
    ports:
      - "5432:5432"
    

  consumer.service:
    image: consumer.service
    build:
      context: .
      dockerfile: Consumer.Service/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - rabbitMQ