version: '3'

services:
  publication.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  consumer.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

