version: '3'

services:
  consumer.service:
    image: consumer.service
    build:
      context: .
      dockerfile: Consumer.Service/Dockerfile
    ports:
      - "8000:80"
    depends_on: 
      - rabbitMQ
  rabbitMQ:
    image: "rabbitmq:3-management"   
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"